import { Tdata, dataTrajectory,checks } from './tableData';

/*idrpCheck:checks[]=[
    {
      "category":"vital sign",
      "purpose":"Data Quality",
      "description":"Review for duplicate visits (same date different visit name) in EDC",
      "visit":"",
      "role":"CDR",
      "method":"Analytics",
      "frequency":"Monthly",
      "owner":"John Smith",
      "checkName":"Lorem Ipsusm",
      "queryText":"",
      "source":"Template 001",
    },
    {
        "category":"vital sign",
        "purpose":"Data Quality",
        "description":"Review dates against the protocol defined windows and for logic.",
        "visit":"",
        "role":"CDR",
        "method":"LSH Edit Checks, Analytics",
        "frequency":"Monthly",
        "owner":"John Smith",
        "checkName":"Lorem Ipsusm",
        "queryText":"",
        "source":"Study M3422",
    },
    {
        "category":"vital sign",
        "purpose":"Data Quality",
        "description":"Review for appropriate protocol adherence, sequence of events and logic.  If an unscheduled visit occurs, check for any time-associated procedures (i.e. AEs, pregnancy, ECG, CXR) or entered in error query site to correct",
        "visit":"",
        "role":"Remote Monitor",
        "method":"Manual",
        "frequency":"Upon unscheduled Visit ",
        "owner":"John Smith",
        "checkName":"Lorem Ipsusm",
        "queryText":"",
        "source":"Template 554 - Modified",
    }
]

idrpCheck1:checks[]=[
    {
      "category":"vital sign",
      "purpose":"Data Quality -1",
      "description":"Review for duplicate visits (same date different visit name) in EDC",
      "visit":"",
      "role":"CDR",
      "method":"Analytics",
      "frequency":"Monthly",
      "owner":"Jordan",
      "checkName":"Lorem Ipsusm",
      "queryText":"",
      "source":"Template 001",
    },
    {
        "category":"vital sign",
        "purpose":"Data Quality -1",
        "description":"Review dates against the protocol defined windows and for logic.",
        "visit":"",
        "role":"CDR",
        "method":"LSH Edit Checks, Analytics",
        "frequency":"Monthly",
        "owner":"Jordan",
        "checkName":"Lorem Ipsusm",
        "queryText":"",
        "source":"Study M3422",
    },
    {
        "category":"vital sign",
        "purpose":"Data Quality -1",
        "description":"Review for appropriate protocol adherence, sequence of events and logic.  If an unscheduled visit occurs, check for any time-associated procedures (i.e. AEs, pregnancy, ECG, CXR) or entered in error query site to correct",
        "visit":"",
        "role":"Remote Monitor",
        "method":"Manual",
        "frequency":"Upon unscheduled Visit ",
        "owner":"Jordan",
        "checkName":"Lorem Ipsusm",
        "queryText":"",
        "source":"Template 554 - Modified",
    }
]*/